service: telly-webhook-service

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: post

#custom:
#  customDomain:
#    domainName: ${env:SLS_DOMAIN_NAME}
#    basePath: 'tally'
#    stage: ${self:provider.stage}
#    certificateArn: ${env:ACM_CERTIFICATE_ARN}
#    createRoute53Record: false
